language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_7.gemfile
matrix:
  exclude:
    - rvm: 2.7
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 3.0
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 3.1
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 3.2
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 3.0
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 3.1
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 3.2
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_7.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_7.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_7.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_7.gemfile
